// Stage 4 — players (Coda DB_PlayerCRM → players + player_representations).
// Idempotent: players keyed by coda_row_id (PlayerCRM Row ID); representations
// inserted once per player (WHERE NOT EXISTS). agent_expiry normalized to date
// (month-only -> last day of month, decision 10).
//
// Usage: node scripts/etl/stage4-players.mjs <codaPlayerCsv> > stage4.sql

import { readFileSync } from "node:fs";
import Papa from "papaparse";
import { sqlStr, sqlInt, sqlBool } from "./lib/sql.mjs";

const CSV = process.argv[2];

const MONTHS = {
  jan: 1,
  feb: 2,
  mar: 3,
  apr: 4,
  may: 5,
  jun: 6,
  jul: 7,
  aug: 8,
  sep: 9,
  oct: 10,
  nov: 11,
  dec: 12,
  january: 1,
  february: 2,
  march: 3,
  april: 4,
  june: 6,
  july: 7,
  august: 8,
  september: 9,
  october: 10,
  november: 11,
  december: 12,
};
const lastDay = (y, m) => new Date(Date.UTC(y, m, 0)).getUTCDate();

/** Normalize dirty agent-expiry to an ISO date string, or null. */
function normExpiry(raw) {
  const s = (raw || "").trim();
  if (!s) return null;
  // DD/MM/YYYY
  let m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (m) return `${m[3]}-${m[2].padStart(2, "0")}-${m[1].padStart(2, "0")}`;
  // "Mon YYYY" / "Month YYYY" / "Mon YY"  -> last day of month
  m = s.match(/^([A-Za-z]+)\s+(\d{2,4})$/);
  if (m) {
    const mo = MONTHS[m[1].toLowerCase()];
    if (mo) {
      let y = parseInt(m[2], 10);
      if (y < 100) y += 2000;
      return `${y}-${String(mo).padStart(2, "0")}-${String(lastDay(y, mo)).padStart(2, "0")}`;
    }
  }
  return null; // unparseable -> leave null
}

const rows = Papa.parse(readFileSync(CSV, "utf8").trim(), {
  header: true,
  skipEmptyLines: true,
}).data;

const STEP = {
  step_follow_back: "FOLLOW BACK (1)",
  step_google_alert: "GOOGLE ALERT (2)",
  step_greetings: "GREETINGS (3)",
  step_sales_message: "SALES MESSAGE (4)",
  step_phone_call: "PHONE CALL (5)",
  step_zoom: "ZOOM (6)",
  step_face_to_face: "FACE TO FACE (7)",
  step_contract: "CONTRACT (8)",
};

const players = [];
const reps = [];
for (const r of rows) {
  const name = (r["Player"] || "").trim();
  const rowId = (r["PlayerCRM Row ID"] || "").trim();
  if (!name || !rowId) continue;
  const parts = name.split(/\s+/);
  players.push({
    codaRowId: rowId,
    full: name,
    first: parts[0],
    last: parts.slice(1).join(" ") || null,
    age: r["Age"],
    status: (r["Status"] || "").trim() || null,
    notes: (r["Notes"] || "").trim() || null,
    steps: Object.fromEntries(
      Object.entries(STEP).map(([col, csv]) => [col, r[csv]]),
    ),
  });

  const repCode = (r["REP (Temp Column)"] || r["REP"] || "").trim() || null;
  const expiry = normExpiry(r["Agent Expiry"]);
  if (repCode || expiry) reps.push({ codaRowId: rowId, repCode, expiry });
}

const out = [];
out.push("-- Stage 4: players (generated by stage4-players.mjs)");
out.push("begin;");

const pv = players
  .map(
    (p) =>
      `(${sqlStr(p.codaRowId)}, ${sqlStr(p.full)}, ${sqlStr(p.first)}, ${sqlStr(p.last)}, ${sqlInt(p.age)}, ${sqlStr(p.status)}, ${sqlStr(p.notes)}, ` +
      Object.keys(STEP)
        .map((c) => sqlBool(p.steps[c]))
        .join(", ") +
      `)`,
  )
  .join(",\n  ");
out.push(`insert into public.players (coda_row_id, full_name, first_name, last_name, age_imported, status, notes, ${Object.keys(STEP).join(", ")})
values
  ${pv}
on conflict (coda_row_id) do update set
  full_name = excluded.full_name, first_name = excluded.first_name, last_name = excluded.last_name,
  age_imported = excluded.age_imported, status = excluded.status, notes = excluded.notes,
  ${Object.keys(STEP)
    .map((c) => `${c} = excluded.${c}`)
    .join(", ")},
  updated_at = now();`);

if (reps.length) {
  const rv = reps
    .map(
      (r) =>
        `(${sqlStr(r.codaRowId)}, ${sqlStr(r.repCode)}, ${r.expiry ? `date ${sqlStr(r.expiry)}` : "null"})`,
    )
    .join(",\n  ");
  out.push(`with rep_src(coda_row_id, rep_code, agent_expiry) as (values\n  ${rv}\n)
insert into public.player_representations (player_id, rep_code, agent_expiry, is_current)
select p.id, s.rep_code, s.agent_expiry, true
from rep_src s join public.players p on p.coda_row_id = s.coda_row_id
where not exists (select 1 from public.player_representations pr where pr.player_id = p.id);`);
}

out.push("commit;");
out.push(`-- counts: players=${players.length} reps=${reps.length}`);
process.stdout.write(out.join("\n\n") + "\n");
