// Stage 2 — contact intelligence (crown jewel). Vibecoded `contacts`
// (account_id, sd, hor, gk_coach, notes) → people in `contacts` +
// `company_contacts` (roles), and the intel blurb → `companies.description`.
// Idempotent: contacts keyed by legacy_ref `vibe-intel:<acct>:<role>[:n]`
// (insert WHERE NOT EXISTS); company_contacts via the active partial unique.
//
// Usage: node scripts/etl/stage2-intel.mjs <vibeDbUrl> > stage2.sql

import { execFileSync } from "node:child_process";
import Papa from "papaparse";
import { sqlStr } from "./lib/sql.mjs";

const VIBE_DB = process.argv[2];

const ROLES = [
  ["sd", "sporting_director"],
  ["hor", "head_of_recruitment"],
  ["gk_coach", "gk_coach"],
];
const JUNK = new Set(["football leadership", "tbc", ""]);

const rows = Papa.parse(
  "account_id,sd,hor,gk_coach,notes\n" +
    execFileSync(
      "psql",
      [
        VIBE_DB,
        "--csv",
        "-t",
        "-c",
        "select account_id, sd, hor, gk_coach, notes from contacts",
      ],
      { encoding: "utf8" },
    ),
  { header: true, skipEmptyLines: true },
).data;

/** Clean a raw intel cell into 0+ person names. */
function people(raw) {
  if (!raw) return [];
  return raw
    .split("/")
    .map((p) => p.replace(/\([^)]*\)/g, "").trim()) // drop parentheticals
    .filter((p) => {
      const low = p.toLowerCase();
      return p && !low.startsWith("tbc") && !JUNK.has(low);
    });
}

function splitName(full) {
  const parts = full.split(/\s+/);
  return { first: parts[0], last: parts.slice(1).join(" ") || null };
}

const descriptions = []; // {ref, descr}
const persons = []; // {ref, first, last}
const links = []; // {personRef, acctRef, role}

for (const r of rows) {
  const acct = (r.account_id || "").trim();
  if (!acct) continue;
  if (r.notes && r.notes.trim())
    descriptions.push({ ref: acct, descr: r.notes.trim() });
  for (const [col, role] of ROLES) {
    const names = people(r[col]);
    names.forEach((full, i) => {
      const { first, last } = splitName(full);
      const ref = `vibe-intel:${acct}:${role}${i ? ":" + i : ""}`;
      persons.push({ ref, first, last });
      links.push({ personRef: ref, acctRef: acct, role });
    });
  }
}

const out = [];
out.push("-- Stage 2: contact intelligence (generated by stage2-intel.mjs)");
out.push("begin;");

if (descriptions.length) {
  const v = descriptions
    .map((d) => `(${sqlStr(d.ref)}, ${sqlStr(d.descr)})`)
    .join(",\n  ");
  out.push(`with intel(legacy_ref, descr) as (values\n  ${v}\n)
update public.companies c set description = i.descr, updated_at = now()
from intel i where c.legacy_ref = i.legacy_ref;`);
}

if (persons.length) {
  const v = persons
    .map((p) => `(${sqlStr(p.ref)}, ${sqlStr(p.first)}, ${sqlStr(p.last)})`)
    .join(",\n  ");
  out.push(`with person_src(legacy_ref, first_name, last_name) as (values\n  ${v}\n)
insert into public.contacts (legacy_ref, first_name, last_name)
select s.legacy_ref, s.first_name, s.last_name from person_src s
where not exists (select 1 from public.contacts c where c.legacy_ref = s.legacy_ref);`);
}

if (links.length) {
  const v = links
    .map(
      (l) =>
        `(${sqlStr(l.personRef)}, ${sqlStr(l.acctRef)}, ${sqlStr(l.role)})`,
    )
    .join(",\n  ");
  out.push(`with cc_src(person_ref, acct_ref, role) as (values\n  ${v}\n)
insert into public.company_contacts (company_id, contact_id, role, is_primary, is_current)
select co.id, ct.id, s.role, true, true
from cc_src s
  join public.contacts ct on ct.legacy_ref = s.person_ref
  join public.companies co on co.legacy_ref = s.acct_ref
on conflict (company_id, contact_id, role) where is_current do nothing;`);
}

out.push("commit;");
out.push(
  `-- counts: descriptions=${descriptions.length} persons=${persons.length} links=${links.length}`,
);
process.stdout.write(out.join("\n\n") + "\n");
