// Stage 3 — club staff (Coda DB_ClubStaff → contacts + company_contacts +
// contact_social_profiles). Reuses an existing contact when (club, name)
// already matches a person in the target (per user decision); else creates a
// new contact keyed by legacy_ref `coda-staff:<slug>:<namekey>`.
//
// Usage: node scripts/etl/stage3-staff.mjs <codaStaffCsv> <targetDbUrl> > stage3.sql

import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import Papa from "papaparse";
import { orgKey, nameKey } from "./lib/normalize.mjs";
import { sqlStr, sqlBool, slugify } from "./lib/sql.mjs";

const CODA_STAFF_CSV = process.argv[2];
const TARGET_DB = process.argv[3];

const ROLE_BY_TITLE = {
  "goalkeeper coach": "gk_coach",
  "head of goalkeeping": "gk_coach",
  "sporting director": "sporting_director",
  manager: "manager",
  scout: "scout",
  analyst: "analyst",
  ceo: "ceo",
  "academy coach": "other",
};
const roleFor = (title) =>
  ROLE_BY_TITLE[(title || "").trim().toLowerCase()] || "other";
const instaNorm = (s) => {
  const v = (s || "").trim();
  return v.toUpperCase() === "PRIVATE" ? "Private" : v || null;
};

const parse = (t, hdr) =>
  Papa.parse(hdr ? hdr + "\n" + t : t.trim(), {
    header: true,
    skipEmptyLines: true,
  }).data;

// --- Existing target state: company slugs + (slug::namekey -> nothing needed, we match by legacy_ref-free id) ---
const slugRows = parse(
  execFileSync(
    "psql",
    [
      TARGET_DB,
      "--csv",
      "-t",
      "-c",
      "select slug from public.companies where slug is not null",
    ],
    { encoding: "utf8" },
  ),
  "slug",
);
const slugSet = new Set(slugRows.map((r) => r.slug));

const existRows = parse(
  execFileSync(
    "psql",
    [
      TARGET_DB,
      "--csv",
      "-t",
      "-c",
      "select co.slug, ct.first_name, ct.last_name, ct.id from public.company_contacts cc join public.contacts ct on ct.id=cc.contact_id join public.companies co on co.id=cc.company_id",
    ],
    { encoding: "utf8" },
  ),
  "slug,first_name,last_name,id",
);
const existing = new Map(); // `${slug}::${namekey}` -> contact_id
for (const r of existRows) {
  const k = `${r.slug}::${nameKey(`${r.first_name || ""} ${r.last_name || ""}`)}`;
  if (!existing.has(k)) existing.set(k, r.id);
}

// --- Process staff ---
const staff = parse(readFileSync(CODA_STAFF_CSV, "utf8"));
const newPersons = new Map(); // clref -> {first,last}
const links = new Map(); // dedup key -> {slug, cid, clref, role, title, rel, pref, insta, notes}
const socials = []; // {slug, cid, clref, url}
const unmatchedClubs = new Set();
let staffRows = 0;

for (const r of staff) {
  const name = (r["Name"] || "").trim();
  const club = (r["Club"] || "").trim();
  if (!name || !club) continue;
  const slug = slugify(orgKey(club));
  if (!slugSet.has(slug)) {
    unmatchedClubs.add(club);
    continue;
  }
  staffRows++;
  const nk = nameKey(name);
  const existId = existing.get(`${slug}::${nk}`) || null;
  const clref = existId ? null : `coda-staff:${slug}:${nk}`;
  if (!existId && !newPersons.has(clref)) {
    const parts = name.split(/\s+/);
    newPersons.set(clref, {
      first: parts[0],
      last: parts.slice(1).join(" ") || null,
    });
  }
  const role = roleFor(r["Title"]);
  const linkKey = `${slug}::${existId || clref}::${role}`;
  if (!links.has(linkKey)) {
    links.set(linkKey, {
      slug,
      cid: existId,
      clref,
      role,
      title: (r["Title"] || "").trim() || null,
      rel: (r["Relationship"] || "").trim() || null,
      pref: r["Preferred Contact"],
      insta: instaNorm(r["Insta Status"]),
      notes: (r["Notes"] || "").trim() || null,
    });
  }
  const url = (r["Social Media URLs"] || "").trim();
  if (url) socials.push({ slug, cid: existId, clref, url });
}

// --- Emit ---
const out = [];
out.push("-- Stage 3: club staff (generated by stage3-staff.mjs)");
out.push("begin;");

if (newPersons.size) {
  const v = [...newPersons.entries()]
    .map(
      ([ref, p]) => `(${sqlStr(ref)}, ${sqlStr(p.first)}, ${sqlStr(p.last)})`,
    )
    .join(",\n  ");
  out.push(`with person_src(legacy_ref, first_name, last_name) as (values\n  ${v}\n)
insert into public.contacts (legacy_ref, first_name, last_name)
select s.legacy_ref, s.first_name, s.last_name from person_src s
where not exists (select 1 from public.contacts c where c.legacy_ref = s.legacy_ref);`);
}

if (links.size) {
  const v = [...links.values()]
    .map(
      (l) =>
        `(${sqlStr(l.slug)}, ${l.cid ? l.cid : "null"}, ${sqlStr(l.clref)}, ${sqlStr(l.role)}, ${sqlStr(l.title)}, ${sqlStr(l.rel)}, ${sqlBool(l.pref)}, ${sqlStr(l.insta)}, ${sqlStr(l.notes)})`,
    )
    .join(",\n  ");
  out.push(`with cc_src(company_slug, cid, clref, role, title, rel, pref, insta, notes) as (values\n  ${v}\n)
insert into public.company_contacts (company_id, contact_id, role, title, relationship_status, preferred_contact, instagram_status, notes, is_current)
select co.id, coalesce(s.cid, ct.id), s.role, s.title, s.rel, s.pref, s.insta, s.notes, true
from cc_src s
  join public.companies co on co.slug = s.company_slug
  left join public.contacts ct on ct.legacy_ref = s.clref
where coalesce(s.cid, ct.id) is not null
on conflict (company_id, contact_id, role) where is_current
do update set
  title = coalesce(public.company_contacts.title, excluded.title),
  relationship_status = coalesce(public.company_contacts.relationship_status, excluded.relationship_status),
  preferred_contact = public.company_contacts.preferred_contact or excluded.preferred_contact,
  instagram_status = coalesce(public.company_contacts.instagram_status, excluded.instagram_status),
  notes = coalesce(public.company_contacts.notes, excluded.notes),
  updated_at = now();`);
}

if (socials.length) {
  const v = socials
    .map(
      (s) =>
        `(${s.cid ? s.cid : "null"}, ${sqlStr(s.clref)}, ${sqlStr(s.url)})`,
    )
    .join(",\n  ");
  out.push(`with social_src(cid, clref, url) as (values\n  ${v}\n)
insert into public.contact_social_profiles (contact_id, platform, url)
select coalesce(s.cid, ct.id), 'instagram', s.url
from social_src s left join public.contacts ct on ct.legacy_ref = s.clref
where coalesce(s.cid, ct.id) is not null
on conflict (contact_id, platform, url) do nothing;`);
}

out.push("commit;");
out.push(
  `-- counts: staffRows=${staffRows} newPersons=${newPersons.size} links=${links.size} socials=${socials.length} unmatchedClubs=${unmatchedClubs.size}`,
);
out.push(`-- unmatched clubs: ${[...unmatchedClubs].slice(0, 20).join(" | ")}`);
process.stdout.write(out.join("\n\n") + "\n");
