--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    -- Goalkeeper schema (Phase 1): organisation classification + external IDs.
    kind text not null default 'company',
    ltv bigint,
    updated_at timestamp with time zone not null default now(),
    coda_row_id text,
    legacy_ref text,
    -- Documented organisation kinds (Decision 13: CHECK over inventoried values,
    -- extended by future migration rather than a lookup table for now).
    constraint companies_kind_check check (
        kind in (
            'pro_club', 'federation', 'media', 'agency', 'service',
            'school', 'university', 'grassroots', 'company'
        )
    ),
    -- coda_row_id is reserved for a general organisations table (Decision 14);
    -- the Club CRM Row ID lives in clubs.coda_row_id, never here.
    constraint companies_coda_row_id_key unique (coda_row_id),
    constraint companies_legacy_ref_key unique (legacy_ref)
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Goalkeeper schema (Phase 1): catalogs + clubs
-- New tables for the Goalkeeper Group CRM domain. Added on top of Atomic,
-- never replacing native tables. See ~/projects/data/schema-design/03-canonical-schema.md.
--

-- Configurable product brands (xG / Onesport / Calma / Goalkeeper.com).
create table public.brands (
    id bigint generated by default as identity primary key,
    key text not null unique,
    name text not null,
    accent_color text,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

-- Per-brand ordered pipeline stages (replaces the global configuration.dealStages).
create table public.pipeline_stages (
    id bigint generated by default as identity primary key,
    brand_id bigint not null,
    position smallint not null,
    name text not null,
    slug text not null,
    default_probability smallint,
    is_won boolean not null default false,
    is_lost boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipeline_stages_probability_check check (default_probability between 0 and 100),
    constraint pipeline_stages_brand_position_key unique (brand_id, position),
    constraint pipeline_stages_brand_slug_key unique (brand_id, slug),
    -- Required so deals can carry a composite FK (brand_id, stage_id) guaranteeing
    -- the stage belongs to the deal's brand (Decision 2; deals land in a later phase).
    constraint pipeline_stages_brand_id_key unique (brand_id, id)
);

-- League / competition catalog.
create table public.leagues (
    id bigint generated by default as identity primary key,
    name text not null,
    country text,
    level text,
    coda_label text,
    created_at timestamp with time zone not null default now(),
    constraint leagues_name_country_key unique (name, country)
);

-- Nation lookup (Decision G: lightweight lookup over free text).
create table public.nations (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamp with time zone not null default now()
);

-- Sport taxonomy (Onesport). Catalog left empty in Phase 1 (no inventoried taxonomy).
create table public.sports (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone not null default now()
);

-- Named target lists (junctions added in a later phase).
create table public.target_lists (
    id bigint generated by default as identity primary key,
    name text not null,
    kind text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint target_lists_kind_check check (kind in ('club', 'player', 'mixed')),
    constraint target_lists_name_kind_key unique (name, kind)
);

-- 1:1 extension of companies for club-specific attributes (company_id is PK and FK).
create table public.clubs (
    company_id bigint primary key,
    league_id bigint,
    nation_id bigint,
    crest text,
    keeper_count smallint not null default 0,
    contract_end date,
    hit_list boolean not null default false,
    -- Free text on purpose (Decision 12: xg_status values not fully inventoried).
    xg_status text,
    email_domain text,
    email_pattern text,
    notes text,
    -- Single source of truth for the Club CRM Row ID (Decision 14).
    coda_row_id text unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint clubs_keeper_count_check check (keeper_count >= 0)
);

-- N-N companies <-> brands (replaces vibecoded accounts.brands[]).
create table public.company_brands (
    company_id bigint not null,
    brand_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (company_id, brand_id)
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

-- Goalkeeper schema (Phase 1) foreign keys
alter table public.pipeline_stages
    add constraint pipeline_stages_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

alter table public.clubs
    add constraint clubs_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.clubs
    add constraint clubs_league_id_fkey foreign key (league_id) references public.leagues(id);

alter table public.clubs
    add constraint clubs_nation_id_fkey foreign key (nation_id) references public.nations(id);

alter table public.company_brands
    add constraint company_brands_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.company_brands
    add constraint company_brands_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

-- Goalkeeper schema (Phase 1) indexes
create index companies_kind_idx on public.companies using btree (kind);
create index companies_name_idx on public.companies using btree (name);
create index leagues_name_idx on public.leagues using btree (name);
create index clubs_league_idx on public.clubs using btree (league_id);
create index clubs_nation_idx on public.clubs using btree (nation_id);
create index clubs_xg_status_idx on public.clubs using btree (xg_status);
