--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    -- Goalkeeper schema: companies is the UNIVERSAL ORG (Brendan/Diego org-centric
    -- model). kind = denormalized mirror of the primary org_type (no CHECK: the
    -- source of truth is company_org_types -> org_types, which is extensible).
    kind text,
    -- slug = standardized handle, aligned with GPS conventions (doc 07).
    slug text,
    ltv bigint,
    updated_at timestamp with time zone not null default now(),
    -- coda_row_id reserved for a general org id (Decision 14); the Club CRM Row ID
    -- lives in clubs.coda_row_id, never here.
    coda_row_id text,
    legacy_ref text,
    constraint companies_slug_key unique (slug),
    constraint companies_coda_row_id_key unique (coda_row_id),
    constraint companies_legacy_ref_key unique (legacy_ref)
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    -- Goalkeeper schema (Phase 2): external IDs + updated_at.
    -- coda_row_id unique; legacy_ref NOT unique (no unambiguous per-person legacy id).
    updated_at timestamp with time zone not null default now(),
    coda_row_id text,
    legacy_ref text,
    constraint contacts_coda_row_id_key unique (coda_row_id)
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    -- Goalkeeper schema (Phase 3): brand + relational stage (source of truth) +
    -- probability override + external IDs. The legacy `stage` slug above is kept
    -- for Atomic Kanban compat and synced from stage_id by a trigger.
    -- brand_id/stage_id are NOT NULL (enforced after the 3B backfill, see migrations).
    brand_id bigint not null,
    stage_id bigint not null,
    probability smallint,
    coda_row_id text,
    legacy_ref text,
    constraint deals_probability_check check (probability between 0 and 100),
    constraint deals_legacy_ref_key unique (legacy_ref)
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    -- Goalkeeper schema (Phase 4): contact_id relaxed to nullable; tasks may target
    -- a deal/company/activity instead of (or alongside) a contact. No league_id —
    -- a league is a company (org-centric model).
    contact_id bigint,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint,
    deal_id bigint,
    company_id bigint,
    activity_id bigint,
    -- At least one target including activity_id (Decision 8).
    constraint tasks_target_check check (num_nonnulls(contact_id, deal_id, company_id, activity_id) >= 1)
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Goalkeeper schema (Phase 1): catalogs + clubs
-- New tables for the Goalkeeper Group CRM domain. Added on top of Atomic,
-- never replacing native tables. See ~/projects/data/schema-design/03-canonical-schema.md.
--

-- Configurable product brands (xG / Onesport / Calma / Goalkeeper.com).
create table public.brands (
    id bigint generated by default as identity primary key,
    key text not null unique,
    name text not null,
    accent_color text,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

-- Per-brand ordered pipeline stages (replaces the global configuration.dealStages).
create table public.pipeline_stages (
    id bigint generated by default as identity primary key,
    brand_id bigint not null,
    position smallint not null,
    name text not null,
    slug text not null,
    default_probability smallint,
    is_won boolean not null default false,
    is_lost boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipeline_stages_probability_check check (default_probability between 0 and 100),
    constraint pipeline_stages_brand_position_key unique (brand_id, position),
    constraint pipeline_stages_brand_slug_key unique (brand_id, slug),
    -- Required so deals can carry a composite FK (brand_id, stage_id) guaranteeing
    -- the stage belongs to the deal's brand (Decision 2; deals land in a later phase).
    constraint pipeline_stages_brand_id_key unique (brand_id, id)
);

-- Org-type vocabulary (standardized with GPS). Source of truth for an org's types
-- is company_org_types; companies.kind mirrors the primary one. Leagues are NOT a
-- catalog — they are orgs (companies of type 'league' + a competitions extension).
create table public.org_types (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamp with time zone not null default now()
);

-- Nation lookup (Decision G: lightweight lookup over free text).
create table public.nations (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamp with time zone not null default now()
);

-- Sport taxonomy (Onesport). Catalog left empty in Phase 1 (no inventoried taxonomy).
create table public.sports (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone not null default now()
);

-- Named target lists (junctions added in a later phase).
create table public.target_lists (
    id bigint generated by default as identity primary key,
    name text not null,
    kind text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint target_lists_kind_check check (kind in ('club', 'player', 'mixed')),
    constraint target_lists_name_kind_key unique (name, kind)
);

-- 1:1 extension of companies for club-specific attributes (company_id is PK and FK).
-- The league is now an ORG (league_company_id -> companies), not a lookup.
create table public.clubs (
    company_id bigint primary key,
    league_company_id bigint,
    nation_id bigint,
    crest text,
    keeper_count smallint not null default 0,
    contract_end date,
    hit_list boolean not null default false,
    -- Free text on purpose (Decision 12: xg_status values not fully inventoried).
    xg_status text,
    email_domain text,
    email_pattern text,
    notes text,
    -- Single source of truth for the Club CRM Row ID (Decision 14).
    coda_row_id text unique,
    -- Optional, nullable logical link to the GPS tenant (Decision B). No FK: GPS is
    -- a separate database. Filled by hand on deal-won if useful (doc 07).
    gps_org_id bigint unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint clubs_keeper_count_check check (keeper_count >= 0)
);

-- N-N companies <-> org_types: SOURCE OF TRUTH for an org's types (multi-type).
create table public.company_org_types (
    company_id bigint not null,
    org_type_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (company_id, org_type_id)
);

-- The org->org "weird web": nesting, governance, broadcast rights. Self-referential.
create table public.org_relationships (
    id bigint generated by default as identity primary key,
    from_company_id bigint not null,
    to_company_id bigint not null,
    relationship_type text not null,
    region text,
    is_current boolean not null default true,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    constraint org_relationships_type_check check (relationship_type in
        ('parent_of', 'governs', 'broadcasts', 'affiliated_with', 'owns')),
    constraint org_relationships_no_self_check check (from_company_id <> to_company_id),
    constraint org_relationships_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);

-- 1:1 extension for league/competition orgs.
create table public.competitions (
    company_id bigint primary key,
    level text,
    format text,
    season text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- N-N companies <-> brands (replaces vibecoded accounts.brands[]).
create table public.company_brands (
    company_id bigint not null,
    brand_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (company_id, brand_id)
);

-- Phase 2: rich person<->organisation junction (role, relationship, history).
-- company_contacts is the source of truth for employment; contacts.company_id is a
-- synchronised mirror of the primary current link (Decision 4).
create table public.company_contacts (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    contact_id bigint not null,
    role text not null default 'other',
    title text,
    relationship_status text,
    preferred_contact boolean not null default false,
    instagram_status text,
    linkedin_status text,
    notes text,
    is_primary boolean not null default false,
    is_current boolean not null default true,
    verified_at date,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_contacts_role_check check (role in
        ('sporting_director', 'head_of_recruitment', 'gk_coach', 'head_coach', 'analyst',
         'scout', 'manager', 'ceo', 'sports_secretary', 'agent', 'other')),
    constraint company_contacts_primary_implies_current_check check (is_primary = false or is_current = true),
    constraint company_contacts_current_no_end_check check (is_current = false or end_date is null),
    constraint company_contacts_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);

-- Phase 2: non-LinkedIn social profiles (LinkedIn stays in contacts.linkedin_url).
create table public.contact_social_profiles (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    platform text not null,
    url text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint contact_social_profiles_platform_check check (platform in ('instagram', 'x', 'tiktok', 'other'))
);

-- Phase 3: xG deal modules (junction; PK prevents duplicate module per deal).
create table public.deal_modules (
    deal_id bigint not null,
    module text not null,
    created_at timestamp with time zone not null default now(),
    primary key (deal_id, module),
    constraint deal_modules_module_check check (module in
        ('ongoing_support', 'transfer_market_support', 'opposition_analysis', 'api'))
);

-- Phase 4: structured commercial activity / outreach. No league_id — a league is a
-- company. player_id FK is added with the players table (later phase); the column
-- lives here so the multi-target CHECK already covers it.
create table public.activities (
    id bigint generated by default as identity primary key,
    type text not null,
    channel text,
    status text,
    note text,
    occurred_at timestamp with time zone not null default now(),
    requires_follow_up boolean not null default false,
    follow_up_date timestamp with time zone,
    sales_id bigint,
    company_id bigint,
    contact_id bigint,
    deal_id bigint,
    player_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint activities_target_check check (num_nonnulls(company_id, contact_id, deal_id, player_id) >= 1),
    constraint activities_follow_up_date_check check (requires_follow_up = false or follow_up_date is not null)
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

-- Goalkeeper schema (Phase 1) foreign keys
alter table public.pipeline_stages
    add constraint pipeline_stages_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

alter table public.clubs
    add constraint clubs_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.clubs
    add constraint clubs_league_company_id_fkey foreign key (league_company_id) references public.companies(id);

alter table public.clubs
    add constraint clubs_nation_id_fkey foreign key (nation_id) references public.nations(id);

alter table public.company_org_types
    add constraint company_org_types_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.company_org_types
    add constraint company_org_types_org_type_id_fkey foreign key (org_type_id) references public.org_types(id) on delete cascade;

alter table public.org_relationships
    add constraint org_relationships_from_fkey foreign key (from_company_id) references public.companies(id) on delete cascade;

alter table public.org_relationships
    add constraint org_relationships_to_fkey foreign key (to_company_id) references public.companies(id) on delete cascade;

alter table public.competitions
    add constraint competitions_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.company_brands
    add constraint company_brands_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.company_brands
    add constraint company_brands_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

-- Goalkeeper schema (Phase 2) foreign keys
alter table public.company_contacts
    add constraint company_contacts_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

alter table public.company_contacts
    add constraint company_contacts_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

alter table public.contact_social_profiles
    add constraint contact_social_profiles_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

-- Goalkeeper schema (Phase 3) foreign keys
alter table public.deals
    add constraint deals_brand_id_fkey foreign key (brand_id) references public.brands(id);

-- Composite FK guarantees the stage belongs to the deal's brand (Decision 2).
alter table public.deals
    add constraint deals_brand_stage_fkey foreign key (brand_id, stage_id) references public.pipeline_stages(brand_id, id);

alter table public.deal_modules
    add constraint deal_modules_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete cascade;

-- Goalkeeper schema (Phase 4) foreign keys
alter table public.activities
    add constraint activities_sales_id_fkey foreign key (sales_id) references public.sales(id);
alter table public.activities
    add constraint activities_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.activities
    add constraint activities_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;
alter table public.activities
    add constraint activities_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete cascade;
-- activities.player_id FK is added with the players table (later phase).

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete cascade;
alter table public.tasks
    add constraint tasks_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.tasks
    add constraint tasks_activity_id_fkey foreign key (activity_id) references public.activities(id) on delete cascade;

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

-- Goalkeeper schema (Phase 1) indexes
create index companies_kind_idx on public.companies using btree (kind);
create index companies_name_idx on public.companies using btree (name);
create index clubs_league_idx on public.clubs using btree (league_company_id);
create index clubs_nation_idx on public.clubs using btree (nation_id);
create index clubs_xg_status_idx on public.clubs using btree (xg_status);
create index clubs_gps_org_idx on public.clubs using btree (gps_org_id);
create index company_org_types_company_idx on public.company_org_types using btree (company_id);
create index company_org_types_type_idx on public.company_org_types using btree (org_type_id);
-- One active relationship per (from, to, type, region); NULLS NOT DISTINCT so a
-- null region cannot be duplicated while active.
create unique index org_relationships_active_uniq
    on public.org_relationships (from_company_id, to_company_id, relationship_type, region)
    nulls not distinct where (is_current);
create index org_relationships_from_idx on public.org_relationships using btree (from_company_id);
create index org_relationships_to_idx on public.org_relationships using btree (to_company_id);

-- Goalkeeper schema (Phase 2) indexes
-- No global unique on (company_id, contact_id, role): only one ACTIVE per tuple.
create unique index company_contacts_active_uniq
    on public.company_contacts (company_id, contact_id, role) where (is_current);
create unique index company_contacts_primary_uniq
    on public.company_contacts (contact_id) where (is_primary);
create index company_contacts_company_idx on public.company_contacts using btree (company_id);
create index company_contacts_contact_idx on public.company_contacts using btree (contact_id);
create index company_contacts_current_idx on public.company_contacts using btree (contact_id) where (is_current);
create unique index contact_social_profiles_contact_platform_url_uniq
    on public.contact_social_profiles (contact_id, platform, url);
create index contact_social_profiles_contact_idx on public.contact_social_profiles using btree (contact_id);

-- Goalkeeper schema (Phase 3) indexes
create index deals_brand_idx on public.deals using btree (brand_id);
create index deals_stage_idx on public.deals using btree (stage_id);

-- Goalkeeper schema (Phase 4) indexes
create index activities_company_idx on public.activities using btree (company_id);
create index activities_contact_idx on public.activities using btree (contact_id);
create index activities_deal_idx on public.activities using btree (deal_id);
create index activities_player_idx on public.activities using btree (player_id);
create index activities_sales_idx on public.activities using btree (sales_id);
create index activities_occurred_at_idx on public.activities using btree (occurred_at);
-- One auto follow-up task per activity.
create unique index tasks_activity_id_uniq on public.tasks (activity_id) where (activity_id is not null);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create index tasks_company_id_idx on public.tasks using btree (company_id);
