-- Goalkeeper schema — Phase 1, migration 1: base catalogs.
--
-- Creates the dependency-free catalog tables (brands, pipeline_stages, org_types,
-- nations, sports, target_lists) with RLS + policies + grants in the same
-- migration (Decision 10), then seeds the inventoried reference data (brands,
-- per-brand pipeline stages, and the org-type vocabulary standardized with GPS).
-- Additive only; no historical migration is touched.
-- NOTE: leagues are NOT a catalog — they are orgs (companies of type 'league'
-- + a competitions extension). See doc 03/06.

--
-- Tables
--

create table public.brands (
    id bigint generated by default as identity primary key,
    key text not null unique,
    name text not null,
    accent_color text,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table public.pipeline_stages (
    id bigint generated by default as identity primary key,
    brand_id bigint not null,
    position smallint not null,
    name text not null,
    slug text not null,
    default_probability smallint,
    is_won boolean not null default false,
    is_lost boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint pipeline_stages_probability_check check (default_probability between 0 and 100),
    constraint pipeline_stages_brand_position_key unique (brand_id, position),
    constraint pipeline_stages_brand_slug_key unique (brand_id, slug),
    -- Enables the future composite FK deals(brand_id, stage_id) (Decision 2).
    constraint pipeline_stages_brand_id_key unique (brand_id, id)
);

-- Org-type vocabulary (standardized with GPS). Multi-type orgs live in
-- company_org_types (migration 2); companies.kind mirrors the primary type.
create table public.org_types (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamp with time zone not null default now()
);

create table public.nations (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamp with time zone not null default now()
);

create table public.sports (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone not null default now()
);

create table public.target_lists (
    id bigint generated by default as identity primary key,
    name text not null,
    kind text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint target_lists_kind_check check (kind in ('club', 'player', 'mixed')),
    constraint target_lists_name_kind_key unique (name, kind)
);

--
-- Foreign keys
--

alter table public.pipeline_stages
    add constraint pipeline_stages_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

--
-- Row Level Security + policies (Decision 10: enabled in the creating migration)
--

alter table public.brands enable row level security;
alter table public.pipeline_stages enable row level security;
alter table public.org_types enable row level security;
alter table public.nations enable row level security;
alter table public.sports enable row level security;
alter table public.target_lists enable row level security;

-- Brands
create policy "Enable read access for authenticated users" on public.brands for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.brands for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.brands for update to authenticated using (true) with check (true);
create policy "Brands Delete Policy" on public.brands for delete to authenticated using (true);

-- Pipeline stages
create policy "Enable read access for authenticated users" on public.pipeline_stages for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.pipeline_stages for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.pipeline_stages for update to authenticated using (true) with check (true);
create policy "Pipeline Stages Delete Policy" on public.pipeline_stages for delete to authenticated using (true);

-- Org types
create policy "Enable read access for authenticated users" on public.org_types for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.org_types for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.org_types for update to authenticated using (true) with check (true);
create policy "Org Types Delete Policy" on public.org_types for delete to authenticated using (true);

-- Nations
create policy "Enable read access for authenticated users" on public.nations for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.nations for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.nations for update to authenticated using (true) with check (true);
create policy "Nations Delete Policy" on public.nations for delete to authenticated using (true);

-- Sports
create policy "Enable read access for authenticated users" on public.sports for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.sports for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.sports for update to authenticated using (true) with check (true);
create policy "Sports Delete Policy" on public.sports for delete to authenticated using (true);

-- Target lists
create policy "Enable read access for authenticated users" on public.target_lists for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.target_lists for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.target_lists for update to authenticated using (true) with check (true);
create policy "Target Lists Delete Policy" on public.target_lists for delete to authenticated using (true);

--
-- Grants (mirror Atomic: all API roles get table privileges; anon stays blocked
-- by the absence of an anon RLS policy)
--

grant all on table public.brands to anon;
grant all on table public.brands to authenticated;
grant all on table public.brands to service_role;

grant all on table public.pipeline_stages to anon;
grant all on table public.pipeline_stages to authenticated;
grant all on table public.pipeline_stages to service_role;

grant all on table public.org_types to anon;
grant all on table public.org_types to authenticated;
grant all on table public.org_types to service_role;

grant all on table public.nations to anon;
grant all on table public.nations to authenticated;
grant all on table public.nations to service_role;

grant all on table public.sports to anon;
grant all on table public.sports to authenticated;
grant all on table public.sports to service_role;

grant all on table public.target_lists to anon;
grant all on table public.target_lists to authenticated;
grant all on table public.target_lists to service_role;

grant all on sequence public.brands_id_seq to anon;
grant all on sequence public.brands_id_seq to authenticated;
grant all on sequence public.brands_id_seq to service_role;

grant all on sequence public.pipeline_stages_id_seq to anon;
grant all on sequence public.pipeline_stages_id_seq to authenticated;
grant all on sequence public.pipeline_stages_id_seq to service_role;

grant all on sequence public.org_types_id_seq to anon;
grant all on sequence public.org_types_id_seq to authenticated;
grant all on sequence public.org_types_id_seq to service_role;

grant all on sequence public.nations_id_seq to anon;
grant all on sequence public.nations_id_seq to authenticated;
grant all on sequence public.nations_id_seq to service_role;

grant all on sequence public.sports_id_seq to anon;
grant all on sequence public.sports_id_seq to authenticated;
grant all on sequence public.sports_id_seq to service_role;

grant all on sequence public.target_lists_id_seq to anon;
grant all on sequence public.target_lists_id_seq to authenticated;
grant all on sequence public.target_lists_id_seq to service_role;

--
-- Seeds (idempotent reference data — lives in the migration so it reaches every
-- environment, unlike supabase/seed.sql which only runs on local db reset).
--

-- Brands: official names + accent palette (CRM-REQUIREMENTS.md §1 / §9.1).
insert into public.brands (key, name, accent_color, is_active) values
    ('xg', 'Goalkeeper xG', '#FF0092', true),
    ('onesport', 'Onesport', '#9B1B30', true),
    ('calma', 'Calma Goalkeeping', '#CEAD54', true),
    ('gkcom', 'Goalkeeper.com', '#00F07B', true)
on conflict (key) do update set
    name = excluded.name,
    accent_color = excluded.accent_color,
    is_active = excluded.is_active;

-- Org-type vocabulary, standardized with GPS (extensible — Brendan: "continue to
-- add to that org-type table"). Every football entity we track/sell to is an org
-- with one or more of these types (source of truth = company_org_types).
insert into public.org_types (code, name) values
    ('club', 'Club'),
    ('league', 'League'),
    ('competition', 'Competition'),
    ('federation', 'Federation'),
    ('national_team', 'National Team'),
    ('broadcaster', 'Broadcaster'),
    ('rights_holder', 'Rights Holder'),
    ('agency', 'Agency'),
    ('media_outlet', 'Media Outlet'),
    ('service', 'Service'),
    ('school', 'School'),
    ('university', 'University'),
    ('grassroots', 'Grassroots'),
    ('company', 'Company')
on conflict (code) do update set name = excluded.name;

-- Pipeline stages: the exact per-brand ordered sets from CRM-REQUIREMENTS.md §3.1
-- (FR-PIPE-2), confirmed against STAGES in goalkeeper-crm-v2/src/lib/data/types.ts.
-- position is 0-indexed to match the vibecoded deals.stage convention.
-- default_probability follows the project's documented derivation
-- (goalkeeper-crm-v2 outreach modal): round(position / (stage_count - 1) * 100).
-- No "lost" stage exists in any documented set, so is_lost is false everywhere;
-- the final stage of each brand is the won stage.
insert into public.pipeline_stages (brand_id, position, name, slug, default_probability, is_won, is_lost)
select b.id, v.position::smallint, v.name, v.slug, v.default_probability::smallint, v.is_won, v.is_lost
from (
    values
        -- xG (8 stages, divisor 7)
        ('xg', 0, 'Target', 'target', 0, false, false),
        ('xg', 1, 'Initial Conversation', 'initial-conversation', 14, false, false),
        ('xg', 2, 'Re Engage', 're-engage', 29, false, false),
        ('xg', 3, 'Demo', 'demo', 43, false, false),
        ('xg', 4, 'Qualified To Buy', 'qualified-to-buy', 57, false, false),
        ('xg', 5, 'Proposal Sent', 'proposal-sent', 71, false, false),
        ('xg', 6, 'Decision Maker Bought-In', 'decision-maker-bought-in', 86, false, false),
        ('xg', 7, 'Closed Won', 'closed-won', 100, true, false),
        -- Onesport (6 stages, divisor 5)
        ('onesport', 0, 'Prospect', 'prospect', 0, false, false),
        ('onesport', 1, 'Contact made', 'contact-made', 20, false, false),
        ('onesport', 2, 'Sample sent', 'sample-sent', 40, false, false),
        ('onesport', 3, 'Quote issued', 'quote-issued', 60, false, false),
        ('onesport', 4, 'PO received', 'po-received', 80, false, false),
        ('onesport', 5, 'Shipped / Won', 'shipped-won', 100, true, false),
        -- Calma (6 stages, divisor 5; same set as Onesport per §3.1)
        ('calma', 0, 'Prospect', 'prospect', 0, false, false),
        ('calma', 1, 'Contact made', 'contact-made', 20, false, false),
        ('calma', 2, 'Sample sent', 'sample-sent', 40, false, false),
        ('calma', 3, 'Quote issued', 'quote-issued', 60, false, false),
        ('calma', 4, 'PO received', 'po-received', 80, false, false),
        ('calma', 5, 'Shipped / Won', 'shipped-won', 100, true, false),
        -- Goalkeeper.com (6 stages, divisor 5)
        ('gkcom', 0, 'Lead', 'lead', 0, false, false),
        ('gkcom', 1, 'Qualified', 'qualified', 20, false, false),
        ('gkcom', 2, 'Meeting booked', 'meeting-booked', 40, false, false),
        ('gkcom', 3, 'Proposal sent', 'proposal-sent', 60, false, false),
        ('gkcom', 4, 'Negotiation', 'negotiation', 80, false, false),
        ('gkcom', 5, 'Closed Won', 'closed-won', 100, true, false)
) as v(brand_key, position, name, slug, default_probability, is_won, is_lost)
join public.brands b on b.key = v.brand_key
on conflict (brand_id, slug) do update set
    position = excluded.position,
    name = excluded.name,
    default_probability = excluded.default_probability,
    is_won = excluded.is_won,
    is_lost = excluded.is_lost;
