-- Goalkeeper schema — Phase 6: players and their relations.
--
-- players + N-N to orgs (clubs AND national teams, non-exclusive), citizenships,
-- representation (agency=org + agent=person), social profiles, and target-list
-- junction. Also adds the deferred activities.player_id FK (column created in the
-- activities migration). Depends on migration 2 (companies) and 5 (activities).
-- Additive; RLS+policies+grants per table.

--
-- 1. players (funnel = 8 boolean columns; status derived from them — Decision D)
--
create table public.players (
    id bigint generated by default as identity primary key,
    full_name text not null,
    first_name text,
    last_name text,
    date_of_birth date,
    age_imported smallint,
    -- 8-step outreach funnel (Coda DB_PlayerCRM). status is derivable from these.
    step_follow_back boolean not null default false,
    step_google_alert boolean not null default false,
    step_greetings boolean not null default false,
    step_sales_message boolean not null default false,
    step_phone_call boolean not null default false,
    step_zoom boolean not null default false,
    step_face_to_face boolean not null default false,
    step_contract boolean not null default false,
    status text,
    notes text,
    coda_row_id text unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
create index players_name_idx on public.players using btree (full_name);
create index players_status_idx on public.players using btree (status);

--
-- 2. player_org_assignments — N-N player<->org (club or national team).
--    Non-exclusive rows (owned + current + national_team can coexist). org_id ->
--    companies (a national team is an org, not a club). App keeps org_id to a
--    club/national_team org.
--
create table public.player_org_assignments (
    id bigint generated by default as identity primary key,
    player_id bigint not null,
    org_id bigint not null,
    relationship_type text not null,
    is_current boolean not null default true,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    constraint player_org_assignments_type_check check (relationship_type in
        ('owned', 'current', 'loaned_in', 'loaned_out', 'target', 'national_team')),
    constraint player_org_assignments_current_no_end_check check (is_current = false or end_date is null),
    constraint player_org_assignments_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);
alter table public.player_org_assignments
    add constraint player_org_assignments_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;
alter table public.player_org_assignments
    add constraint player_org_assignments_org_id_fkey foreign key (org_id) references public.companies(id) on delete cascade;
-- No global unique (allows two distinct loans in different periods); one active
-- relationship per (player, org, type).
create unique index player_org_assignments_active_uniq
    on public.player_org_assignments (player_id, org_id, relationship_type) where (is_current);
create index player_org_assignments_player_idx on public.player_org_assignments using btree (player_id);
create index player_org_assignments_org_idx on public.player_org_assignments using btree (org_id);

--
-- 3. player_citizenships — N-N player<->nation (a player can have several).
--
create table public.player_citizenships (
    player_id bigint not null,
    nation_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (player_id, nation_id)
);
alter table public.player_citizenships
    add constraint player_citizenships_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;
alter table public.player_citizenships
    add constraint player_citizenships_nation_id_fkey foreign key (nation_id) references public.nations(id) on delete cascade;

--
-- 4. player_representations — agency (org) + agent (person).
--
create table public.player_representations (
    id bigint generated by default as identity primary key,
    player_id bigint not null,
    agency_company_id bigint,
    agent_contact_id bigint,
    rep_code text,
    agent_expiry date,
    is_current boolean not null default true,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    constraint player_representations_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);
alter table public.player_representations
    add constraint player_representations_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;
alter table public.player_representations
    add constraint player_representations_agency_company_id_fkey foreign key (agency_company_id) references public.companies(id);
alter table public.player_representations
    add constraint player_representations_agent_contact_id_fkey foreign key (agent_contact_id) references public.contacts(id);
create index player_representations_player_idx on public.player_representations using btree (player_id);

--
-- 5. player_social_profiles (same shape as contact_social_profiles).
--
create table public.player_social_profiles (
    id bigint generated by default as identity primary key,
    player_id bigint not null,
    platform text not null,
    url text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint player_social_profiles_platform_check check (platform in ('instagram', 'x', 'tiktok', 'other'))
);
alter table public.player_social_profiles
    add constraint player_social_profiles_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;
create unique index player_social_profiles_player_platform_url_uniq
    on public.player_social_profiles (player_id, platform, url);
create index player_social_profiles_player_idx on public.player_social_profiles using btree (player_id);

--
-- 6. player_target_lists — N-N player<->target_list.
--
create table public.player_target_lists (
    target_list_id bigint not null,
    player_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (target_list_id, player_id)
);
alter table public.player_target_lists
    add constraint player_target_lists_target_list_id_fkey foreign key (target_list_id) references public.target_lists(id) on delete cascade;
alter table public.player_target_lists
    add constraint player_target_lists_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

--
-- 7. Deferred FK: activities.player_id -> players (column created in migration 5).
--
alter table public.activities
    add constraint activities_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

--
-- Row Level Security + policies
--
alter table public.players enable row level security;
alter table public.player_org_assignments enable row level security;
alter table public.player_citizenships enable row level security;
alter table public.player_representations enable row level security;
alter table public.player_social_profiles enable row level security;
alter table public.player_target_lists enable row level security;

create policy "Enable read access for authenticated users" on public.players for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.players for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.players for update to authenticated using (true) with check (true);
create policy "Players Delete Policy" on public.players for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.player_org_assignments for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.player_org_assignments for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.player_org_assignments for update to authenticated using (true) with check (true);
create policy "Player Org Assignments Delete Policy" on public.player_org_assignments for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.player_citizenships for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.player_citizenships for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.player_citizenships for update to authenticated using (true) with check (true);
create policy "Player Citizenships Delete Policy" on public.player_citizenships for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.player_representations for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.player_representations for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.player_representations for update to authenticated using (true) with check (true);
create policy "Player Representations Delete Policy" on public.player_representations for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.player_social_profiles for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.player_social_profiles for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.player_social_profiles for update to authenticated using (true) with check (true);
create policy "Player Social Profiles Delete Policy" on public.player_social_profiles for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.player_target_lists for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.player_target_lists for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.player_target_lists for update to authenticated using (true) with check (true);
create policy "Player Target Lists Delete Policy" on public.player_target_lists for delete to authenticated using (true);

--
-- Grants (identity sequences: players, player_org_assignments, player_representations,
-- player_social_profiles; the two composite-PK junctions have none)
--
grant all on table public.players to anon;
grant all on table public.players to authenticated;
grant all on table public.players to service_role;

grant all on table public.player_org_assignments to anon;
grant all on table public.player_org_assignments to authenticated;
grant all on table public.player_org_assignments to service_role;

grant all on table public.player_citizenships to anon;
grant all on table public.player_citizenships to authenticated;
grant all on table public.player_citizenships to service_role;

grant all on table public.player_representations to anon;
grant all on table public.player_representations to authenticated;
grant all on table public.player_representations to service_role;

grant all on table public.player_social_profiles to anon;
grant all on table public.player_social_profiles to authenticated;
grant all on table public.player_social_profiles to service_role;

grant all on table public.player_target_lists to anon;
grant all on table public.player_target_lists to authenticated;
grant all on table public.player_target_lists to service_role;

grant all on sequence public.players_id_seq to anon;
grant all on sequence public.players_id_seq to authenticated;
grant all on sequence public.players_id_seq to service_role;

grant all on sequence public.player_org_assignments_id_seq to anon;
grant all on sequence public.player_org_assignments_id_seq to authenticated;
grant all on sequence public.player_org_assignments_id_seq to service_role;

grant all on sequence public.player_representations_id_seq to anon;
grant all on sequence public.player_representations_id_seq to authenticated;
grant all on sequence public.player_representations_id_seq to service_role;

grant all on sequence public.player_social_profiles_id_seq to anon;
grant all on sequence public.player_social_profiles_id_seq to authenticated;
grant all on sequence public.player_social_profiles_id_seq to service_role;
