-- Goalkeeper schema — Phase 4: activities + tasks extension + follow-up automation.
--
-- Creates the structured commercial-activity table, extends tasks with optional
-- targets (contact/deal/company/activity), and auto-generates exactly one
-- follow-up task per activity that requires one. There is NO league_id: a league
-- is a company (org-centric model), so league outreach targets it via company_id.
-- activities carries a player_id column; its FK is added in migration 6 (players).
-- Additive; no historical migration touched.

--
-- 1. activities
--
create table public.activities (
    id bigint generated by default as identity primary key,
    type text not null,
    channel text,
    status text,
    note text,
    occurred_at timestamp with time zone not null default now(),
    requires_follow_up boolean not null default false,
    follow_up_date timestamp with time zone,
    sales_id bigint,
    company_id bigint,
    contact_id bigint,
    deal_id bigint,
    -- player_id FK is added in migration 6 (players); column lives here so the
    -- target CHECK already covers it.
    player_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    -- At least one target (Decision 9: "at least one", not "exactly one").
    constraint activities_target_check check (num_nonnulls(company_id, contact_id, deal_id, player_id) >= 1),
    -- A follow-up needs a date.
    constraint activities_follow_up_date_check check (requires_follow_up = false or follow_up_date is not null)
);

alter table public.activities
    add constraint activities_sales_id_fkey foreign key (sales_id) references public.sales(id);
alter table public.activities
    add constraint activities_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.activities
    add constraint activities_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;
alter table public.activities
    add constraint activities_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete cascade;

create index activities_company_idx on public.activities using btree (company_id);
create index activities_contact_idx on public.activities using btree (contact_id);
create index activities_deal_idx on public.activities using btree (deal_id);
create index activities_player_idx on public.activities using btree (player_id);
create index activities_sales_idx on public.activities using btree (sales_id);
create index activities_occurred_at_idx on public.activities using btree (occurred_at);

alter table public.activities enable row level security;
create policy "Enable read access for authenticated users" on public.activities for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.activities for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.activities for update to authenticated using (true) with check (true);
create policy "Activities Delete Policy" on public.activities for delete to authenticated using (true);

grant all on table public.activities to anon;
grant all on table public.activities to authenticated;
grant all on table public.activities to service_role;
grant all on sequence public.activities_id_seq to anon;
grant all on sequence public.activities_id_seq to authenticated;
grant all on sequence public.activities_id_seq to service_role;

--
-- 2. Extend tasks (contact_id becomes nullable; new optional targets)
--
alter table public.tasks alter column contact_id drop not null;
alter table public.tasks add column deal_id bigint;
alter table public.tasks add column company_id bigint;
alter table public.tasks add column activity_id bigint;

alter table public.tasks
    add constraint tasks_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete cascade;
alter table public.tasks
    add constraint tasks_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.tasks
    add constraint tasks_activity_id_fkey foreign key (activity_id) references public.activities(id) on delete cascade;

-- At least one target including activity_id (Decision 8). No league_id — a league
-- is a company, so a league task targets it via company_id.
alter table public.tasks
    add constraint tasks_target_check check (num_nonnulls(contact_id, deal_id, company_id, activity_id) >= 1);

-- One auto follow-up task per activity.
create unique index tasks_activity_id_uniq on public.tasks (activity_id) where (activity_id is not null);
create index tasks_deal_id_idx on public.tasks using btree (deal_id);
create index tasks_company_id_idx on public.tasks using btree (company_id);

--
-- 3. Follow-up automation
--
-- An activity with requires_follow_up=true owns exactly one follow-up task (the
-- unique partial index enforces "at most one"; this function enforces "exactly
-- one when required"). Deactivation policy: if requires_follow_up flips to false,
-- the auto-task is deleted ONLY if not yet completed (done_date is null); a
-- completed follow-up is preserved as history. Writes only to tasks (no path back
-- into activities), so no recursion is possible.
--
create or replace function private.gk_handle_activity_followup() returns trigger
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    v_task_id bigint;
begin
    select id into v_task_id from public.tasks where activity_id = new.id;

    if new.requires_follow_up then
        if v_task_id is null then
            insert into public.tasks (contact_id, company_id, deal_id, activity_id, type, text, due_date, sales_id)
            values (new.contact_id, new.company_id, new.deal_id, new.id, 'follow-up',
                    'Follow up: ' || new.type, new.follow_up_date, new.sales_id);
        else
            update public.tasks
               set due_date = new.follow_up_date,
                   contact_id = new.contact_id,
                   company_id = new.company_id,
                   deal_id = new.deal_id
             where id = v_task_id and done_date is null;
        end if;
    else
        if v_task_id is not null then
            delete from public.tasks where id = v_task_id and done_date is null;
        end if;
    end if;
    return null;
end;
$$;

revoke execute on function private.gk_handle_activity_followup() from public;

-- Fires only on the columns that affect a follow-up, so editing note/status/etc.
-- never creates or duplicates a task.
create trigger gk_activities_followup
    after insert or update of requires_follow_up, follow_up_date, contact_id, company_id, deal_id, sales_id
    on public.activities
    for each row execute function private.gk_handle_activity_followup();

--
-- 4. merge_contacts(): reassign the loser's activities to the winner before the
-- loser is deleted, so the contact_id ON DELETE CASCADE does not destroy them.
-- (activities has no unique on contact_id, so a plain reassignment is safe.)
--
CREATE OR REPLACE FUNCTION "public"."merge_contacts"("loser_id" bigint, "winner_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
  deal_record RECORD;
  cc_record RECORD;
  merged_emails jsonb;
  merged_phones jsonb;
  merged_tags bigint[];
  winner_emails jsonb;
  loser_emails jsonb;
  winner_phones jsonb;
  loser_phones jsonb;
  email_map jsonb;
  phone_map jsonb;
  winner_has_primary boolean;
  prev_sync text;
BEGIN
  -- Fetch both contacts
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  -- 1. Reassign tasks from loser to winner
  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 2. Reassign contact notes from loser to winner
  UPDATE contact_notes SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 3. Update deals - replace loser with winner in contact_ids array
  FOR deal_record IN
    SELECT id, contact_ids
    FROM deals
    WHERE contact_ids @> ARRAY[loser_id]
  LOOP
    UPDATE deals
    SET contact_ids = (
      SELECT ARRAY(
        SELECT DISTINCT unnest(
          array_remove(deal_record.contact_ids, loser_id) || ARRAY[winner_id]
        )
      )
    )
    WHERE id = deal_record.id;
  END LOOP;

  -- 3a. Reassign activities from loser to winner (before the loser is deleted,
  -- so contact_id ON DELETE CASCADE does not destroy them).
  UPDATE activities SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 3b. Reassign contact_social_profiles; drop loser duplicates of (platform, url).
  DELETE FROM contact_social_profiles l
  WHERE l.contact_id = loser_id
    AND EXISTS (
      SELECT 1 FROM contact_social_profiles w
      WHERE w.contact_id = winner_id AND w.platform = l.platform AND w.url = l.url
    );
  UPDATE contact_social_profiles SET contact_id = winner_id, updated_at = now()
  WHERE contact_id = loser_id;

  -- 3c. Reassign company_contacts with deterministic conflict resolution.
  -- Suppress the mirror sync while we shuffle rows; recompute once at the end.
  prev_sync := coalesce(current_setting('gk.sync_active', true), '');
  PERFORM set_config('gk.sync_active', '1', true);

  winner_has_primary := EXISTS (SELECT 1 FROM company_contacts WHERE contact_id = winner_id AND is_primary);

  -- If the winner already owns the primary, the loser's primary yields to it.
  IF winner_has_primary THEN
    UPDATE company_contacts SET is_primary = false, updated_at = now()
    WHERE contact_id = loser_id AND is_primary;
  END IF;

  -- Resolve ACTIVE conflicts: loser active row whose (company_id, role) collides
  -- with a winner active row. Winner values win; loser fills the gaps; notes are
  -- concatenated when both differ; the primary flag transfers only if the winner
  -- has none. Then the loser row is removed (its data was folded in).
  FOR cc_record IN
    SELECT l.* FROM company_contacts l
    WHERE l.contact_id = loser_id AND l.is_current
      AND EXISTS (
        SELECT 1 FROM company_contacts w
        WHERE w.contact_id = winner_id AND w.is_current
          AND w.company_id = l.company_id AND w.role = l.role
      )
  LOOP
    UPDATE company_contacts w SET
      title = coalesce(w.title, cc_record.title),
      relationship_status = coalesce(w.relationship_status, cc_record.relationship_status),
      instagram_status = coalesce(w.instagram_status, cc_record.instagram_status),
      linkedin_status = coalesce(w.linkedin_status, cc_record.linkedin_status),
      preferred_contact = w.preferred_contact OR cc_record.preferred_contact,
      verified_at = greatest(w.verified_at, cc_record.verified_at),
      start_date = least(w.start_date, cc_record.start_date),
      notes = CASE
                WHEN w.notes IS NULL THEN cc_record.notes
                WHEN cc_record.notes IS NULL THEN w.notes
                WHEN w.notes = cc_record.notes THEN w.notes
                ELSE w.notes || E'\n---\n' || cc_record.notes
              END,
      is_primary = w.is_primary OR (cc_record.is_primary AND NOT winner_has_primary),
      updated_at = now()
    WHERE w.contact_id = winner_id AND w.is_current
      AND w.company_id = cc_record.company_id AND w.role = cc_record.role;
    DELETE FROM company_contacts WHERE id = cc_record.id;
  END LOOP;

  -- Move the remaining loser rows (non-conflicting active + all historical).
  UPDATE company_contacts SET contact_id = winner_id, updated_at = now()
  WHERE contact_id = loser_id;

  PERFORM set_config('gk.sync_active', prev_sync, true);

  -- 3d. External IDs: keep the winner's; borrow the loser's only when the winner
  -- lacks one. Clear the loser's coda_row_id first to avoid a transient unique clash.
  IF winner_contact.coda_row_id IS NULL AND loser_contact.coda_row_id IS NOT NULL THEN
    UPDATE contacts SET coda_row_id = NULL WHERE id = loser_id;
  END IF;

  -- 4. Merge contact data

  -- Get email arrays
  winner_emails := COALESCE(winner_contact.email_jsonb, '[]'::jsonb);
  loser_emails := COALESCE(loser_contact.email_jsonb, '[]'::jsonb);

  -- Merge emails with deduplication by email address
  -- Build a map of email -> email object, then convert back to array
  email_map := '{}'::jsonb;

  -- Add winner emails to map
  IF jsonb_array_length(winner_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_emails)-1 LOOP
      email_map := email_map || jsonb_build_object(
        winner_emails->i->>'email',
        winner_emails->i
      );
    END LOOP;
  END IF;

  -- Add loser emails to map (won't overwrite existing keys)
  IF jsonb_array_length(loser_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_emails)-1 LOOP
      IF NOT email_map ? (loser_emails->i->>'email') THEN
        email_map := email_map || jsonb_build_object(
          loser_emails->i->>'email',
          loser_emails->i
        );
      END IF;
    END LOOP;
  END IF;

  -- Convert map back to array
  merged_emails := (SELECT jsonb_agg(value) FROM jsonb_each(email_map));
  merged_emails := COALESCE(merged_emails, '[]'::jsonb);

  -- Get phone arrays
  winner_phones := COALESCE(winner_contact.phone_jsonb, '[]'::jsonb);
  loser_phones := COALESCE(loser_contact.phone_jsonb, '[]'::jsonb);

  -- Merge phones with deduplication by number
  phone_map := '{}'::jsonb;

  -- Add winner phones to map
  IF jsonb_array_length(winner_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_phones)-1 LOOP
      phone_map := phone_map || jsonb_build_object(
        winner_phones->i->>'number',
        winner_phones->i
      );
    END LOOP;
  END IF;

  -- Add loser phones to map (won't overwrite existing keys)
  IF jsonb_array_length(loser_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_phones)-1 LOOP
      IF NOT phone_map ? (loser_phones->i->>'number') THEN
        phone_map := phone_map || jsonb_build_object(
          loser_phones->i->>'number',
          loser_phones->i
        );
      END IF;
    END LOOP;
  END IF;

  -- Convert map back to array
  merged_phones := (SELECT jsonb_agg(value) FROM jsonb_each(phone_map));
  merged_phones := COALESCE(merged_phones, '[]'::jsonb);

  -- Merge tags (remove duplicates)
  merged_tags := ARRAY(
    SELECT DISTINCT unnest(
      COALESCE(winner_contact.tags, ARRAY[]::bigint[]) ||
      COALESCE(loser_contact.tags, ARRAY[]::bigint[])
    )
  );

  -- 5. Update winner with merged data
  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    gender = COALESCE(winner_contact.gender, loser_contact.gender),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    title = COALESCE(winner_contact.title, loser_contact.title),
    company_id = COALESCE(winner_contact.company_id, loser_contact.company_id),
    email_jsonb = merged_emails,
    phone_jsonb = merged_phones,
    linkedin_url = COALESCE(winner_contact.linkedin_url, loser_contact.linkedin_url),
    background = COALESCE(winner_contact.background, loser_contact.background),
    has_newsletter = COALESCE(winner_contact.has_newsletter, loser_contact.has_newsletter),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    sales_id = COALESCE(winner_contact.sales_id, loser_contact.sales_id),
    tags = merged_tags,
    coda_row_id = COALESCE(winner_contact.coda_row_id, loser_contact.coda_row_id),
    legacy_ref = COALESCE(winner_contact.legacy_ref, loser_contact.legacy_ref)
  WHERE id = winner_id;

  -- 6. Delete loser contact (its relations/profiles/activities were reassigned)
  DELETE FROM contacts WHERE id = loser_id;

  -- 7. Recompute the winner's company mirror from the merged relations
  PERFORM private.gk_apply_primary_company(winner_id);

  RETURN winner_id;
END;
$$;
