-- Goalkeeper schema — Phase 2: contacts relations.
--
-- Extends contacts with external IDs + updated_at, adds the rich person<->org
-- junction company_contacts and contact_social_profiles, keeps contacts.company_id
-- as a synchronised mirror of the primary current link (company_contacts is the
-- source of truth, Decision 4), backfills existing contacts, and teaches
-- merge_contacts() about the new tables. Sync helpers live in the private schema
-- (internal, not exposed as RPC). Additive; RLS+policies+grants in this migration.

--
-- 1. Extend contacts
--
alter table public.contacts add column updated_at timestamp with time zone not null default now();
alter table public.contacts add column coda_row_id text;
alter table public.contacts add column legacy_ref text;
-- coda_row_id identifies one Coda row -> unique. legacy_ref is NOT unique:
-- the previous sources offer no unambiguous per-person legacy id (staff keyed by
-- club+name, not unique).
alter table public.contacts add constraint contacts_coda_row_id_key unique (coda_row_id);

--
-- 2. company_contacts (rich person<->organisation junction)
--
create table public.company_contacts (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    contact_id bigint not null,
    role text not null default 'other',
    title text,
    relationship_status text,                       -- free text (Decision 12)
    preferred_contact boolean not null default false,
    instagram_status text,                          -- free text (Decision 12)
    linkedin_status text,                           -- free text (Decision 12)
    notes text,
    is_primary boolean not null default false,
    is_current boolean not null default true,
    verified_at date,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_contacts_role_check check (role in
        ('sporting_director', 'head_of_recruitment', 'gk_coach', 'head_coach', 'analyst',
         'scout', 'manager', 'ceo', 'sports_secretary', 'agent', 'other')),
    -- a primary link must be current
    constraint company_contacts_primary_implies_current_check check (is_primary = false or is_current = true),
    -- a current link has no end date
    constraint company_contacts_current_no_end_check check (is_current = false or end_date is null),
    -- coherent date order
    constraint company_contacts_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);

alter table public.company_contacts
    add constraint company_contacts_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.company_contacts
    add constraint company_contacts_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

-- No global unique on (company_id, contact_id, role): a person may leave an org and
-- return to the same role years later. Only one ACTIVE relationship per tuple.
create unique index company_contacts_active_uniq
    on public.company_contacts (company_id, contact_id, role) where (is_current);
-- Exactly one primary link per contact.
create unique index company_contacts_primary_uniq
    on public.company_contacts (contact_id) where (is_primary);
create index company_contacts_company_idx on public.company_contacts using btree (company_id);
create index company_contacts_contact_idx on public.company_contacts using btree (contact_id);
create index company_contacts_current_idx on public.company_contacts using btree (contact_id) where (is_current);

--
-- 3. contact_social_profiles (LinkedIn stays in contacts.linkedin_url; others here)
--
create table public.contact_social_profiles (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    platform text not null,
    url text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint contact_social_profiles_platform_check check (platform in ('instagram', 'x', 'tiktok', 'other'))
);

alter table public.contact_social_profiles
    add constraint contact_social_profiles_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete cascade;

-- Allow multiple accounts per platform, block exact duplicate URLs.
create unique index contact_social_profiles_contact_platform_url_uniq
    on public.contact_social_profiles (contact_id, platform, url);
create index contact_social_profiles_contact_idx on public.contact_social_profiles using btree (contact_id);

--
-- 4. Private sync helpers
--
-- Recursion guard: a transaction-local GUC gk.sync_active='1' is set around every
-- cross-table write so the opposite trigger early-returns. Each setter saves and
-- restores the previous value, so nesting is safe and the flag never escapes the
-- transaction (set_config(..., is_local => true)).

-- Generic updated_at setter (single reusable function for all three tables).
create or replace function private.gk_set_updated_at() returns trigger
    language plpgsql
    set search_path to ''
    as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- Recompute contacts.company_id from the single primary+current company_contact.
create or replace function private.gk_apply_primary_company(p_contact_id bigint) returns void
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    v_company_id bigint;
    v_prev text;
begin
    select cc.company_id into v_company_id
    from public.company_contacts cc
    where cc.contact_id = p_contact_id and cc.is_primary and cc.is_current
    limit 1;

    v_prev := coalesce(current_setting('gk.sync_active', true), '');
    perform set_config('gk.sync_active', '1', true);
    update public.contacts c
       set company_id = v_company_id
     where c.id = p_contact_id
       and c.company_id is distinct from v_company_id;
    perform set_config('gk.sync_active', v_prev, true);
end;
$$;

-- Atomically make one company_contact the contact's primary link.
create or replace function private.gk_set_primary_company_contact(p_company_contact_id bigint) returns void
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    v_contact_id bigint;
    v_is_current boolean;
    v_prev text;
begin
    select contact_id, is_current into v_contact_id, v_is_current
    from public.company_contacts where id = p_company_contact_id;

    if v_contact_id is null then
        raise exception 'company_contact % not found', p_company_contact_id;
    end if;
    if not v_is_current then
        raise exception 'cannot set a non-current company_contact (%) as primary', p_company_contact_id;
    end if;

    v_prev := coalesce(current_setting('gk.sync_active', true), '');
    perform set_config('gk.sync_active', '1', true);
    update public.company_contacts
       set is_primary = false, updated_at = now()
     where contact_id = v_contact_id and is_primary and id <> p_company_contact_id;
    update public.company_contacts
       set is_primary = true, updated_at = now()
     where id = p_company_contact_id and is_primary is distinct from true;
    perform set_config('gk.sync_active', v_prev, true);

    perform private.gk_apply_primary_company(v_contact_id);
end;
$$;

-- Reflect an Atomic-side contacts.company_id change into company_contacts.
-- Deterministic: keep an existing primary link to that company; else promote the
-- lowest-id current link; else create one with role='other'.
create or replace function private.gk_set_primary_company_for_contact(p_contact_id bigint, p_company_id bigint) returns void
    language plpgsql security definer
    set search_path to ''
    as $$
declare
    v_prev text;
    v_target_id bigint;
begin
    v_prev := coalesce(current_setting('gk.sync_active', true), '');
    perform set_config('gk.sync_active', '1', true);

    if p_company_id is null then
        update public.company_contacts
           set is_primary = false, updated_at = now()
         where contact_id = p_contact_id and is_primary;
    else
        select id into v_target_id
        from public.company_contacts
        where contact_id = p_contact_id and company_id = p_company_id and is_current and is_primary
        order by id limit 1;

        if v_target_id is null then
            select id into v_target_id
            from public.company_contacts
            where contact_id = p_contact_id and company_id = p_company_id and is_current
            order by id limit 1;
        end if;

        if v_target_id is null then
            insert into public.company_contacts (company_id, contact_id, role, is_primary, is_current)
            values (p_company_id, p_contact_id, 'other', false, true)
            returning id into v_target_id;
        end if;

        update public.company_contacts
           set is_primary = false, updated_at = now()
         where contact_id = p_contact_id and is_primary and id <> v_target_id;
        update public.company_contacts
           set is_primary = true, updated_at = now()
         where id = v_target_id and is_primary is distinct from true;
    end if;

    perform set_config('gk.sync_active', v_prev, true);
    perform private.gk_apply_primary_company(p_contact_id);
end;
$$;

-- Trigger: company_contacts change -> recompute contacts.company_id mirror.
create or replace function private.gk_sync_primary_company() returns trigger
    language plpgsql security definer
    set search_path to ''
    as $$
begin
    if coalesce(current_setting('gk.sync_active', true), '') = '1' then
        if tg_op = 'DELETE' then return old; else return new; end if;
    end if;

    if tg_op = 'DELETE' then
        perform private.gk_apply_primary_company(old.contact_id);
        return old;
    end if;

    perform private.gk_apply_primary_company(new.contact_id);
    if tg_op = 'UPDATE' and new.contact_id is distinct from old.contact_id then
        perform private.gk_apply_primary_company(old.contact_id);
    end if;
    return new;
end;
$$;

-- Trigger: Atomic-side contacts.company_id change -> create/promote company_contacts.
create or replace function private.gk_bridge_contact_company() returns trigger
    language plpgsql security definer
    set search_path to ''
    as $$
begin
    if coalesce(current_setting('gk.sync_active', true), '') = '1' then
        return new;
    end if;
    if tg_op = 'UPDATE' and new.company_id is not distinct from old.company_id then
        return new;
    end if;
    if tg_op = 'INSERT' and new.company_id is null then
        return new;
    end if;

    perform private.gk_set_primary_company_for_contact(new.id, new.company_id);
    return new;
end;
$$;

--
-- 5. Triggers
--
create trigger set_contacts_updated_at
    before update on public.contacts
    for each row execute function private.gk_set_updated_at();

create trigger set_company_contacts_updated_at
    before update on public.company_contacts
    for each row execute function private.gk_set_updated_at();

create trigger set_contact_social_profiles_updated_at
    before update on public.contact_social_profiles
    for each row execute function private.gk_set_updated_at();

create trigger gk_company_contacts_sync
    after insert or delete or update of company_id, contact_id, is_primary, is_current
    on public.company_contacts
    for each row execute function private.gk_sync_primary_company();

create trigger gk_contacts_company_bridge
    after insert or update of company_id on public.contacts
    for each row execute function private.gk_bridge_contact_company();

--
-- 6. Row Level Security + policies (single-tenant; anon denied by absence of policy)
--
alter table public.company_contacts enable row level security;
alter table public.contact_social_profiles enable row level security;

create policy "Enable read access for authenticated users" on public.company_contacts for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.company_contacts for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.company_contacts for update to authenticated using (true) with check (true);
create policy "Company Contacts Delete Policy" on public.company_contacts for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.contact_social_profiles for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.contact_social_profiles for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.contact_social_profiles for update to authenticated using (true) with check (true);
create policy "Contact Social Profiles Delete Policy" on public.contact_social_profiles for delete to authenticated using (true);

--
-- 7. Grants (tables + identity sequences). Private sync functions stay internal:
-- REVOKE EXECUTE FROM PUBLIC and no grants to anon/authenticated/service_role.
--
grant all on table public.company_contacts to anon;
grant all on table public.company_contacts to authenticated;
grant all on table public.company_contacts to service_role;

grant all on table public.contact_social_profiles to anon;
grant all on table public.contact_social_profiles to authenticated;
grant all on table public.contact_social_profiles to service_role;

grant all on sequence public.company_contacts_id_seq to anon;
grant all on sequence public.company_contacts_id_seq to authenticated;
grant all on sequence public.company_contacts_id_seq to service_role;

grant all on sequence public.contact_social_profiles_id_seq to anon;
grant all on sequence public.contact_social_profiles_id_seq to authenticated;
grant all on sequence public.contact_social_profiles_id_seq to service_role;

revoke execute on function private.gk_set_updated_at() from public;
revoke execute on function private.gk_apply_primary_company(bigint) from public;
revoke execute on function private.gk_set_primary_company_contact(bigint) from public;
revoke execute on function private.gk_set_primary_company_for_contact(bigint, bigint) from public;
revoke execute on function private.gk_sync_primary_company() from public;
revoke execute on function private.gk_bridge_contact_company() from public;

--
-- 8. Backfill existing contacts (company_id mirror -> primary current link).
-- Suppress the sync trigger: the mirror is already correct by construction.
--
select set_config('gk.sync_active', '1', true);

insert into public.company_contacts (company_id, contact_id, role, is_primary, is_current)
select c.company_id, c.id, 'other', true, true
from public.contacts c
where c.company_id is not null;

select set_config('gk.sync_active', '', true);

-- Fail loudly if the backfill produced more than one primary per contact.
do $$
declare
    v_bad int;
begin
    select count(*) into v_bad
    from (
        select contact_id from public.company_contacts where is_primary group by contact_id having count(*) > 1
    ) x;
    if v_bad > 0 then
        raise exception 'backfill produced % contact(s) with more than one primary company_contact', v_bad;
    end if;
end;
$$;

--
-- 9. merge_contacts(): teach it about company_contacts, contact_social_profiles,
-- coda_row_id and legacy_ref. Signature, language and security are preserved.
--
CREATE OR REPLACE FUNCTION "public"."merge_contacts"("loser_id" bigint, "winner_id" bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  winner_contact contacts%ROWTYPE;
  loser_contact contacts%ROWTYPE;
  deal_record RECORD;
  cc_record RECORD;
  merged_emails jsonb;
  merged_phones jsonb;
  merged_tags bigint[];
  winner_emails jsonb;
  loser_emails jsonb;
  winner_phones jsonb;
  loser_phones jsonb;
  email_map jsonb;
  phone_map jsonb;
  winner_has_primary boolean;
  prev_sync text;
BEGIN
  -- Fetch both contacts
  SELECT * INTO winner_contact FROM contacts WHERE id = winner_id;
  SELECT * INTO loser_contact FROM contacts WHERE id = loser_id;

  IF winner_contact IS NULL OR loser_contact IS NULL THEN
    RAISE EXCEPTION 'Contact not found';
  END IF;

  -- 1. Reassign tasks from loser to winner
  UPDATE tasks SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 2. Reassign contact notes from loser to winner
  UPDATE contact_notes SET contact_id = winner_id WHERE contact_id = loser_id;

  -- 3. Update deals - replace loser with winner in contact_ids array
  FOR deal_record IN
    SELECT id, contact_ids
    FROM deals
    WHERE contact_ids @> ARRAY[loser_id]
  LOOP
    UPDATE deals
    SET contact_ids = (
      SELECT ARRAY(
        SELECT DISTINCT unnest(
          array_remove(deal_record.contact_ids, loser_id) || ARRAY[winner_id]
        )
      )
    )
    WHERE id = deal_record.id;
  END LOOP;

  -- 3b. Reassign contact_social_profiles; drop loser duplicates of (platform, url).
  DELETE FROM contact_social_profiles l
  WHERE l.contact_id = loser_id
    AND EXISTS (
      SELECT 1 FROM contact_social_profiles w
      WHERE w.contact_id = winner_id AND w.platform = l.platform AND w.url = l.url
    );
  UPDATE contact_social_profiles SET contact_id = winner_id, updated_at = now()
  WHERE contact_id = loser_id;

  -- 3c. Reassign company_contacts with deterministic conflict resolution.
  -- Suppress the mirror sync while we shuffle rows; recompute once at the end.
  prev_sync := coalesce(current_setting('gk.sync_active', true), '');
  PERFORM set_config('gk.sync_active', '1', true);

  winner_has_primary := EXISTS (SELECT 1 FROM company_contacts WHERE contact_id = winner_id AND is_primary);

  -- If the winner already owns the primary, the loser's primary yields to it.
  IF winner_has_primary THEN
    UPDATE company_contacts SET is_primary = false, updated_at = now()
    WHERE contact_id = loser_id AND is_primary;
  END IF;

  -- Resolve ACTIVE conflicts: loser active row whose (company_id, role) collides
  -- with a winner active row. Winner values win; loser fills the gaps; notes are
  -- concatenated when both differ; the primary flag transfers only if the winner
  -- has none. Then the loser row is removed (its data was folded in).
  FOR cc_record IN
    SELECT l.* FROM company_contacts l
    WHERE l.contact_id = loser_id AND l.is_current
      AND EXISTS (
        SELECT 1 FROM company_contacts w
        WHERE w.contact_id = winner_id AND w.is_current
          AND w.company_id = l.company_id AND w.role = l.role
      )
  LOOP
    UPDATE company_contacts w SET
      title = coalesce(w.title, cc_record.title),
      relationship_status = coalesce(w.relationship_status, cc_record.relationship_status),
      instagram_status = coalesce(w.instagram_status, cc_record.instagram_status),
      linkedin_status = coalesce(w.linkedin_status, cc_record.linkedin_status),
      preferred_contact = w.preferred_contact OR cc_record.preferred_contact,
      verified_at = greatest(w.verified_at, cc_record.verified_at),
      start_date = least(w.start_date, cc_record.start_date),
      notes = CASE
                WHEN w.notes IS NULL THEN cc_record.notes
                WHEN cc_record.notes IS NULL THEN w.notes
                WHEN w.notes = cc_record.notes THEN w.notes
                ELSE w.notes || E'\n---\n' || cc_record.notes
              END,
      is_primary = w.is_primary OR (cc_record.is_primary AND NOT winner_has_primary),
      updated_at = now()
    WHERE w.contact_id = winner_id AND w.is_current
      AND w.company_id = cc_record.company_id AND w.role = cc_record.role;
    DELETE FROM company_contacts WHERE id = cc_record.id;
  END LOOP;

  -- Move the remaining loser rows (non-conflicting active + all historical).
  UPDATE company_contacts SET contact_id = winner_id, updated_at = now()
  WHERE contact_id = loser_id;

  PERFORM set_config('gk.sync_active', prev_sync, true);

  -- 3d. External IDs: keep the winner's; borrow the loser's only when the winner
  -- lacks one. Clear the loser's coda_row_id first to avoid a transient unique clash.
  IF winner_contact.coda_row_id IS NULL AND loser_contact.coda_row_id IS NOT NULL THEN
    UPDATE contacts SET coda_row_id = NULL WHERE id = loser_id;
  END IF;

  -- 4. Merge contact data

  -- Get email arrays
  winner_emails := COALESCE(winner_contact.email_jsonb, '[]'::jsonb);
  loser_emails := COALESCE(loser_contact.email_jsonb, '[]'::jsonb);

  -- Merge emails with deduplication by email address
  email_map := '{}'::jsonb;

  IF jsonb_array_length(winner_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_emails)-1 LOOP
      email_map := email_map || jsonb_build_object(
        winner_emails->i->>'email',
        winner_emails->i
      );
    END LOOP;
  END IF;

  IF jsonb_array_length(loser_emails) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_emails)-1 LOOP
      IF NOT email_map ? (loser_emails->i->>'email') THEN
        email_map := email_map || jsonb_build_object(
          loser_emails->i->>'email',
          loser_emails->i
        );
      END IF;
    END LOOP;
  END IF;

  merged_emails := (SELECT jsonb_agg(value) FROM jsonb_each(email_map));
  merged_emails := COALESCE(merged_emails, '[]'::jsonb);

  -- Get phone arrays
  winner_phones := COALESCE(winner_contact.phone_jsonb, '[]'::jsonb);
  loser_phones := COALESCE(loser_contact.phone_jsonb, '[]'::jsonb);

  phone_map := '{}'::jsonb;

  IF jsonb_array_length(winner_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(winner_phones)-1 LOOP
      phone_map := phone_map || jsonb_build_object(
        winner_phones->i->>'number',
        winner_phones->i
      );
    END LOOP;
  END IF;

  IF jsonb_array_length(loser_phones) > 0 THEN
    FOR i IN 0..jsonb_array_length(loser_phones)-1 LOOP
      IF NOT phone_map ? (loser_phones->i->>'number') THEN
        phone_map := phone_map || jsonb_build_object(
          loser_phones->i->>'number',
          loser_phones->i
        );
      END IF;
    END LOOP;
  END IF;

  merged_phones := (SELECT jsonb_agg(value) FROM jsonb_each(phone_map));
  merged_phones := COALESCE(merged_phones, '[]'::jsonb);

  -- Merge tags (remove duplicates)
  merged_tags := ARRAY(
    SELECT DISTINCT unnest(
      COALESCE(winner_contact.tags, ARRAY[]::bigint[]) ||
      COALESCE(loser_contact.tags, ARRAY[]::bigint[])
    )
  );

  -- 5. Update winner with merged data
  UPDATE contacts SET
    avatar = COALESCE(winner_contact.avatar, loser_contact.avatar),
    gender = COALESCE(winner_contact.gender, loser_contact.gender),
    first_name = COALESCE(winner_contact.first_name, loser_contact.first_name),
    last_name = COALESCE(winner_contact.last_name, loser_contact.last_name),
    title = COALESCE(winner_contact.title, loser_contact.title),
    company_id = COALESCE(winner_contact.company_id, loser_contact.company_id),
    email_jsonb = merged_emails,
    phone_jsonb = merged_phones,
    linkedin_url = COALESCE(winner_contact.linkedin_url, loser_contact.linkedin_url),
    background = COALESCE(winner_contact.background, loser_contact.background),
    has_newsletter = COALESCE(winner_contact.has_newsletter, loser_contact.has_newsletter),
    first_seen = LEAST(COALESCE(winner_contact.first_seen, loser_contact.first_seen), COALESCE(loser_contact.first_seen, winner_contact.first_seen)),
    last_seen = GREATEST(COALESCE(winner_contact.last_seen, loser_contact.last_seen), COALESCE(loser_contact.last_seen, winner_contact.last_seen)),
    sales_id = COALESCE(winner_contact.sales_id, loser_contact.sales_id),
    tags = merged_tags,
    coda_row_id = COALESCE(winner_contact.coda_row_id, loser_contact.coda_row_id),
    legacy_ref = COALESCE(winner_contact.legacy_ref, loser_contact.legacy_ref)
  WHERE id = winner_id;

  -- 6. Delete loser contact (its relations/profiles were already reassigned)
  DELETE FROM contacts WHERE id = loser_id;

  -- 7. Recompute the winner's company mirror from the merged relations
  PERFORM private.gk_apply_primary_company(winner_id);

  RETURN winner_id;
END;
$$;

--
-- 10. Refresh contacts_summary: keep every existing column/order/behaviour
-- (company_name, nb_tasks, email_fts, phone_fts, security_invoker) and append the
-- three new contact columns at the end (Postgres only allows appending on REPLACE).
--
create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks,
    co.updated_at,
    co.coda_row_id,
    co.legacy_ref
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;
