-- Goalkeeper schema — Phase 1, migration 2: org core (companies = universal org).
--
-- companies becomes the universal org table (Brendan/Diego org-centric model):
-- every football entity (club, league, federation, national team, broadcaster,
-- agency, media, service, school...) is a company with one or more org_types.
-- Adds the multi-type junction (company_org_types, the source of truth for types),
-- the org->org relationship web (org_relationships), the 1:1 clubs + competitions
-- extensions, company_brands, and the optional GPS reconciliation link
-- (clubs.gps_org_id). Standardization with GPS, NOT a structural merge (doc 07).
-- Depends on migration 1. Additive only.

--
-- 1. Extend companies (universal org)
--
-- kind = denormalized mirror of the primary org_type (quick filter / display).
-- No CHECK: org_types is the source of truth and is extensible (Brendan).
alter table public.companies add column kind text;
-- slug = standardized handle, aligned with GPS conventions.
alter table public.companies add column slug text;
alter table public.companies add column ltv bigint;
alter table public.companies add column updated_at timestamp with time zone not null default now();
alter table public.companies add column coda_row_id text;
alter table public.companies add column legacy_ref text;

alter table public.companies add constraint companies_slug_key unique (slug);
-- coda_row_id reserved for a general org id (Decision 14); the Club CRM Row ID
-- lives in clubs.coda_row_id, never here.
alter table public.companies add constraint companies_coda_row_id_key unique (coda_row_id);
alter table public.companies add constraint companies_legacy_ref_key unique (legacy_ref);

create index companies_kind_idx on public.companies using btree (kind);
create index companies_name_idx on public.companies using btree (name);

--
-- 2. company_org_types — N-N; SOURCE OF TRUTH for an org's types
--    (an org can be several, e.g. a body that is both a league and a federation).
--
create table public.company_org_types (
    company_id bigint not null,
    org_type_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (company_id, org_type_id)
);
alter table public.company_org_types
    add constraint company_org_types_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.company_org_types
    add constraint company_org_types_org_type_id_fkey foreign key (org_type_id) references public.org_types(id) on delete cascade;
create index company_org_types_company_idx on public.company_org_types using btree (company_id);
create index company_org_types_type_idx on public.company_org_types using btree (org_type_id);

--
-- 3. org_relationships — the "weird web": nesting, governance, broadcast rights.
--    Self-referential; both ends are orgs.
--
create table public.org_relationships (
    id bigint generated by default as identity primary key,
    from_company_id bigint not null,
    to_company_id bigint not null,
    relationship_type text not null,
    region text,
    is_current boolean not null default true,
    start_date date,
    end_date date,
    created_at timestamp with time zone not null default now(),
    constraint org_relationships_type_check check (relationship_type in
        ('parent_of', 'governs', 'broadcasts', 'affiliated_with', 'owns')),
    constraint org_relationships_no_self_check check (from_company_id <> to_company_id),
    constraint org_relationships_date_order_check check (start_date is null or end_date is null or start_date <= end_date)
);
alter table public.org_relationships
    add constraint org_relationships_from_fkey foreign key (from_company_id) references public.companies(id) on delete cascade;
alter table public.org_relationships
    add constraint org_relationships_to_fkey foreign key (to_company_id) references public.companies(id) on delete cascade;
-- One active relationship per (from, to, type, region). NULLS NOT DISTINCT so a
-- null region (non geo-split) cannot be duplicated while active.
create unique index org_relationships_active_uniq
    on public.org_relationships (from_company_id, to_company_id, relationship_type, region)
    nulls not distinct where (is_current);
create index org_relationships_from_idx on public.org_relationships using btree (from_company_id);
create index org_relationships_to_idx on public.org_relationships using btree (to_company_id);

--
-- 4. clubs — 1:1 extension for clubs (company_id is PK and FK). The league is now
--    an ORG (league_company_id -> companies), not a lookup.
--
create table public.clubs (
    company_id bigint primary key,
    league_company_id bigint,
    nation_id bigint,
    crest text,
    keeper_count smallint not null default 0,
    contract_end date,
    hit_list boolean not null default false,
    -- Free text on purpose (Decision 12: xg_status values not fully inventoried).
    xg_status text,
    email_domain text,
    email_pattern text,
    notes text,
    -- Single source of truth for the Club CRM Row ID (Decision 14).
    coda_row_id text unique,
    -- Optional, nullable logical link to the GPS tenant (Decision B). No FK:
    -- GPS is a separate database. Filled by hand on deal-won if useful.
    gps_org_id bigint unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint clubs_keeper_count_check check (keeper_count >= 0)
);

alter table public.clubs
    add constraint clubs_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.clubs
    add constraint clubs_league_company_id_fkey foreign key (league_company_id) references public.companies(id);
alter table public.clubs
    add constraint clubs_nation_id_fkey foreign key (nation_id) references public.nations(id);

create index clubs_league_idx on public.clubs using btree (league_company_id);
create index clubs_nation_idx on public.clubs using btree (nation_id);
create index clubs_xg_status_idx on public.clubs using btree (xg_status);
create index clubs_gps_org_idx on public.clubs using btree (gps_org_id);

--
-- 5. competitions — 1:1 extension for league/competition orgs.
--
create table public.competitions (
    company_id bigint primary key,
    level text,
    format text,
    season text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
alter table public.competitions
    add constraint competitions_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

--
-- 6. company_brands (N-N companies <-> brands)
--
create table public.company_brands (
    company_id bigint not null,
    brand_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (company_id, brand_id)
);
alter table public.company_brands
    add constraint company_brands_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
alter table public.company_brands
    add constraint company_brands_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete cascade;

--
-- Row Level Security + policies (Decision 10)
--
alter table public.company_org_types enable row level security;
alter table public.org_relationships enable row level security;
alter table public.clubs enable row level security;
alter table public.competitions enable row level security;
alter table public.company_brands enable row level security;

-- Company org types
create policy "Enable read access for authenticated users" on public.company_org_types for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.company_org_types for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.company_org_types for update to authenticated using (true) with check (true);
create policy "Company Org Types Delete Policy" on public.company_org_types for delete to authenticated using (true);

-- Org relationships
create policy "Enable read access for authenticated users" on public.org_relationships for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.org_relationships for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.org_relationships for update to authenticated using (true) with check (true);
create policy "Org Relationships Delete Policy" on public.org_relationships for delete to authenticated using (true);

-- Clubs
create policy "Enable read access for authenticated users" on public.clubs for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.clubs for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.clubs for update to authenticated using (true) with check (true);
create policy "Clubs Delete Policy" on public.clubs for delete to authenticated using (true);

-- Competitions
create policy "Enable read access for authenticated users" on public.competitions for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.competitions for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.competitions for update to authenticated using (true) with check (true);
create policy "Competitions Delete Policy" on public.competitions for delete to authenticated using (true);

-- Company brands
create policy "Enable read access for authenticated users" on public.company_brands for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.company_brands for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.company_brands for update to authenticated using (true) with check (true);
create policy "Company Brands Delete Policy" on public.company_brands for delete to authenticated using (true);

--
-- Grants (only org_relationships has an identity sequence)
--
grant all on table public.company_org_types to anon;
grant all on table public.company_org_types to authenticated;
grant all on table public.company_org_types to service_role;

grant all on table public.org_relationships to anon;
grant all on table public.org_relationships to authenticated;
grant all on table public.org_relationships to service_role;

grant all on table public.clubs to anon;
grant all on table public.clubs to authenticated;
grant all on table public.clubs to service_role;

grant all on table public.competitions to anon;
grant all on table public.competitions to authenticated;
grant all on table public.competitions to service_role;

grant all on table public.company_brands to anon;
grant all on table public.company_brands to authenticated;
grant all on table public.company_brands to service_role;

grant all on sequence public.org_relationships_id_seq to anon;
grant all on sequence public.org_relationships_id_seq to authenticated;
grant all on sequence public.org_relationships_id_seq to service_role;

--
-- Refresh companies_summary to expose the new columns. Existing columns and the
-- nb_deals / nb_contacts behaviour are unchanged; security_invoker is preserved.
--
create or replace view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts,
    -- New columns appended at the end so CREATE OR REPLACE VIEW preserves the
    -- existing leading columns (Postgres only allows appending to a replaced view).
    c.kind,
    c.ltv,
    c.updated_at,
    c.coda_row_id,
    c.legacy_ref,
    c.slug
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;
