-- Goalkeeper schema — Phase 7: Onesport teams + target-list junctions.
--
-- teams (1-N under an org) + team_sports (N-N to the sports catalog) +
-- org_target_lists (any org can be on a named target list). sports and
-- target_lists already exist (migration 1). Depends on migrations 1 and 2.
-- Additive; RLS+policies+grants per table.

--
-- teams (Onesport unit nested under an org)
--
create table public.teams (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    name text,
    level text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint teams_level_check check (level in ('grassroots', 'school', 'university', 'club'))
);
alter table public.teams
    add constraint teams_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;
create index teams_company_idx on public.teams using btree (company_id);

--
-- team_sports — N-N team<->sport
--
create table public.team_sports (
    team_id bigint not null,
    sport_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (team_id, sport_id)
);
alter table public.team_sports
    add constraint team_sports_team_id_fkey foreign key (team_id) references public.teams(id) on delete cascade;
alter table public.team_sports
    add constraint team_sports_sport_id_fkey foreign key (sport_id) references public.sports(id) on delete cascade;

--
-- org_target_lists — N-N target_list<->org (any org: club, league, etc.)
--
create table public.org_target_lists (
    target_list_id bigint not null,
    company_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (target_list_id, company_id)
);
alter table public.org_target_lists
    add constraint org_target_lists_target_list_id_fkey foreign key (target_list_id) references public.target_lists(id) on delete cascade;
alter table public.org_target_lists
    add constraint org_target_lists_company_id_fkey foreign key (company_id) references public.companies(id) on delete cascade;

--
-- Row Level Security + policies
--
alter table public.teams enable row level security;
alter table public.team_sports enable row level security;
alter table public.org_target_lists enable row level security;

create policy "Enable read access for authenticated users" on public.teams for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.teams for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.teams for update to authenticated using (true) with check (true);
create policy "Teams Delete Policy" on public.teams for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.team_sports for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.team_sports for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.team_sports for update to authenticated using (true) with check (true);
create policy "Team Sports Delete Policy" on public.team_sports for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.org_target_lists for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.org_target_lists for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.org_target_lists for update to authenticated using (true) with check (true);
create policy "Org Target Lists Delete Policy" on public.org_target_lists for delete to authenticated using (true);

--
-- Grants (only teams has an identity sequence)
--
grant all on table public.teams to anon;
grant all on table public.teams to authenticated;
grant all on table public.teams to service_role;

grant all on table public.team_sports to anon;
grant all on table public.team_sports to authenticated;
grant all on table public.team_sports to service_role;

grant all on table public.org_target_lists to anon;
grant all on table public.org_target_lists to authenticated;
grant all on table public.org_target_lists to service_role;

grant all on sequence public.teams_id_seq to anon;
grant all on sequence public.teams_id_seq to authenticated;
grant all on sequence public.teams_id_seq to service_role;
